
export type Destination = {
    id: string;
    city: string;
    country: string;
    label: string;
    type: 'city' | 'country';
};

const rawDestinations: Omit<Destination, 'id' | 'label'>[] = [
  // Cities
  { city: "Cairo", country: "Egypt", type: "city" },
  { city: "Johannesburg", country: "South Africa", type: "city" },
  { city: "Addis Ababa", country: "Ethiopia", type: "city" },
  { city: "Casablanca", country: "Morocco", type: "city" },
  { city: "Cape Town", country: "South Africa", type: "city" },
  { city: "Nairobi", country: "Kenya", type: "city" },
  { city: "Lagos", country: "Nigeria", type: "city" },
  { city: "Tunis", country: "Tunisia", type: "city" },
  { city: "Sharm el-Sheikh", country: "Egypt", type: "city" },
  { city: "Abuja", country: "Nigeria", type: "city" },
  { city: "Windhoek", country: "Namibia", type: "city" },
  { city: "Dar es Salaam", country: "Tanzania", type: "city" },
  { city: "Kigali", country: "Rwanda", type: "city" },
  { city: "Entebbe", country: "Uganda", type: "city" },
  { city: "Lusaka", country: "Zambia", type: "city" },
  { city: "Lome", country: "Togo", type: "city" },
  { city: "Dakar", country: "Senegal", type: "city" },
  { city: "Accra", country: "Ghana", type: "city" },
  { city: "Mombasa", country: "Kenya", type: "city" },
  { city: "Zanzibar City", country: "Tanzania", type: "city" },
  { city: "Victoria Falls", country: "Zimbabwe", type: "city" },
  { city: "Swakopmund", country: "Namibia", type: "city" },
  { city: "Bamako", country: "Mali", type: "city" },
  { city: "Maputo", country: "Mozambique", type: "city" },
  { city: "Harare", country: "Zimbabwe", type: "city" },
  { city: "Monastir", country: "Tunisia", type: "city" },
  { city: "Hurghada", country: "Egypt", type: "city" },
  { city: "Marrakech", country: "Morocco", type: "city" },
  { city: "Agadir", country: "Morocco", type: "city" },
  { city: "Douala", country: "Cameroon", type: "city" },
  { city: "Abidjan", country: "Côte d’Ivoire", type: "city" },
  { city: "Algiers", country: "Algeria", type: "city" },
  { city: "Freetown", country: "Sierra Leone", type: "city" },
  { city: "Mogadishu", country: "Somalia", type: "city" },
  { city: "Blantyre", country: "Malawi", type: "city" },
  { city: "Kano", country: "Nigeria", type: "city" },
  { city: "Ibadan", country: "Nigeria", type: "city" },
  { city: "Port Louis", country: "Mauritius", type: "city" },
  { city: "Antananarivo", country: "Madagascar", type: "city" },
  { city: "Kampala", country: "Uganda", type: "city" },
  { city: "Tripoli", country: "Libya", type: "city" },
  { city: "Conakry", country: "Guinea", type: "city" },
  { city: "Ndola", country: "Zambia", type: "city" },
  { city: "Kumasi", country: "Ghana", type: "city" },
  { city: "Kilimanjaro", country: "Tanzania", type: "city" },
  { city: "Malabo", country: "Equatorial Guinea", type: "city" },
  { city: "Luanda", country: "Angola", type: "city" },
  { city: "Port Elizabeth", country: "South Africa", type: "city" },
  { city: "George", country: "South Africa", type: "city" },
  { city: "Durban", country: "South Africa", type: "city" },
  // Countries
  { city: "Egypt", country: "Egypt", type: "country" },
  { city: "South Africa", country: "South Africa", type: "country" },
  { city: "Ethiopia", country: "Ethiopia", type: "country" },
  { city: "Morocco", country: "Morocco", type: "country" },
  { city: "Kenya", country: "Kenya", type: "country" },
  { city: "Nigeria", country: "Nigeria", type: "country" },
  { city: "Tunisia", country: "Tunisia", type: "country" },
  { city: "Uganda", country: "Uganda", type: "country" },
  { city: "Tanzania", country: "Tanzania", type: "country" },
  { city: "Zimbabwe", country: "Zimbabwe", type: "country" },
  { city: "Namibia", country: "Namibia", type: "country" },
  { city: "Ghana", country: "Ghana", type: "country" },
  { city: "Senegal", country: "Senegal", type: "country" },
  { city: "Rwanda", country: "Rwanda", type: "country" },
  { city: "Zambia", country: "Zambia", type: "country" },
  { city: "Côte d’Ivoire", country: "Côte d’Ivoire", type: "country" },
  { city: "Algeria", country: "Algeria", type: "country" },
  { city: "Mozambique", country: "Mozambique", type: "country" },
  { city: "Sierra Leone", country: "Sierra Leone", type: "country" },
  { city: "Somalia", country: "Somalia", type: "country" },
  { city: "Malawi", country: "Malawi", type: "country" },
  { city: "Libya", country: "Libya", type: "country" },
  { city: "Guinea", country: "Guinea", type: "country" },
  { city: "Equatorial Guinea", country: "Equatorial Guinea", type: "country" },
  { city: "Angola", country: "Angola", type: "country" },
  { city: "Madagascar", country: "Madagascar", type: "country" },
  { city: "Mauritius", country: "Mauritius", type: "country" },
  { city: "Botswana", country: "Botswana", type: "country" },
  { city: "Seychelles", country: "Seychelles", type: "country" },
  { city: "Mali", country: "Mali", type: "country" },
  { city: "Burkina Faso", country: "Burkina Faso", type: "country" },
  { city: "Niger", country: "Niger", type: "country" },
  { city: "Chad", country: "Chad", type: "country" },
  { city: "Sudan", country: "Sudan", type: "country" },
  { city: "South Sudan", country: "South Sudan", type: "country" },
  { city: "Eritrea", country: "Eritrea", type: "country" },
  { city: "Djibouti", country: "Djibouti", type: "country" },
  { city: "Comoros", country: "Comoros", type: "country" },
  { city: "Cape Verde", country: "Cape Verde", type: "country" },
  { city: "São Tomé and Príncipe", country: "São Tomé and Príncipe", type: "country" },
  { city: "Lesotho", country: "Lesotho", type: "country" },
];

export const destinations: Destination[] = rawDestinations.map((d, index) => {
    const id = `${d.city.toLowerCase().replace(/ /g, '-')}-${index}`;
    const label = d.type === 'city' && d.city !== d.country ? `${d.city} (${d.country})` : d.country;
    return { ...d, id, label };
});
