
export const africanPlaces = [
  // Cities
  { name: "Cairo (Egypt)", type: "city" },
  { name: "Johannesburg (South Africa)", type: "city" },
  { name: "Addis Ababa (Ethiopia)", type: "city" },
  { name: "Casablanca (Morocco)", type: "city" },
  { name: "Cape Town (South Africa)", type: "city" },
  { name: "Nairobi (Kenya)", type: "city" },
  { name: "Lagos (Nigeria)", type: "city" },
  { name: "Tunis (Tunisia)", type: "city" },
  { name: "Sharm el-Sheikh (Egypt)", type: "city" },
  { name: "Abuja (Nigeria)", type: "city" },
  { name: "Windhoek (Namibia)", type: "city" },
  { name: "Dar es Salaam (Tanzania)", type: "city" },
  { name: "Kigali (Rwanda)", type: "city" },
  { name: "Entebbe (Uganda)", type: "city" },
  { name: "Lusaka (Zambia)", type: "city" },
  { name: "Lome (Togo)", type: "city" },
  { name: "Dakar (Senegal)", type: "city" },
  { name: "Accra (Ghana)", type: "city" },
  { name: "Mombasa (Kenya)", type: "city" },
  { name: "Zanzibar / Stone Town (Tanzania)", type: "city" },
  { name: "Victoria Falls (Zimbabwe)", type: "city" },
  { name: "Swakopmund (Namibia)", type: "city" },
  { name: "Bamako (Mali)", type: "city" },
  { name: "Maputo (Mozambique)", type: "city" },
  { name: "Harare (Zimbabwe)", type: "city" },
  { name: "Monastir (Tunisia)", type: "city" },
  { name: "Hurghada (Egypt)", type: "city" },
  { name: "Marrakech (Morocco)", type: "city" },
  { name: "Agadir (Morocco)", type: "city" },
  { name: "Douala (Cameroon)", type: "city" },
  { name: "Abidjan (Côte d’Ivoire)", type: "city" },
  { name: "Algiers (Algeria)", type: "city" },
  { name: "Freetown (Sierra Leone)", type: "city" },
  { name: "Mogadishu (Somalia)", type: "city" },
  { name: "Blantyre (Malawi)", type: "city" },
  { name: "Kano (Nigeria)", type: "city" },
  { name: "Ibadan (Nigeria)", type: "city" },
  { name: "Port Louis (Mauritius)", type: "city" },
  { name: "Antananarivo (Madagascar)", type: "city" },
  { name: "Kampala (Uganda)", type: "city" },
  { name: "Tripoli (Libya)", type: "city" },
  { name: "Conakry (Guinea)", type: "city" },
  { name: "Ndola (Zambia)", type: "city" },
  { name: "Kumasi (Ghana)", type: "city" },
  { name: "Kilimanjaro (Tanzania)", type: "city" },
  { name: "Malabo (Equatorial Guinea)", type: "city" },
  { name: "Luanda (Angola)", type: "city" },
  { name: "Port Elizabeth (South Africa)", type: "city" },
  { name: "George (South Africa)", type: "city" },
  { name: "Durban (South Africa)", type: "city" },
  // Countries
  { name: "Egypt", type: "country" },
  { name: "South Africa", type: "country" },
  { name: "Ethiopia", type: "country" },
  { name: "Morocco", type: "country" },
  { name: "Kenya", type: "country" },
  { name: "Nigeria", type: "country" },
  { name: "Tunisia", type: "country" },
  { name: "Uganda", type: "country" },
  { name: "Tanzania", type: "country" },
  { name: "Zimbabwe", type: "country" },
  { name: "Namibia", type: "country" },
  { name: "Ghana", type: "country" },
  { name: "Senegal", type: "country" },
  { name: "Rwanda", type: "country" },
  { name: "Zambia", type: "country" },
  { name: "Côte d’Ivoire", type: "country" },
  { name: "Algeria", type: "country" },
  { name: "Mozambique", type: "country" },
  { name: "Sierra Leone", type: "country" },
  { name: "Somalia", type: "country" },
  { name: "Malawi", type: "country" },
  { name: "Libya", type: "country" },
  { name: "Guinea", type: "country" },
  { name: "Equatorial Guinea", type: "country" },
  { name: "Angola", type: "country" },
  { name: "Madagascar", type: "country" },
  { name: "Mauritius", type: "country" },
  { name: "Botswana", type: "country" },
  { name: "Seychelles", type: "country" },
  { name: "Mali", type: "country" },
  { name: "Burkina Faso", type: "country" },
  { name: "Niger", type: "country" },
  { name: "Chad", type: "country" },
  { name: "Sudan", type: "country" },
  { name: "South Sudan", type: "country" },
  { name: "Eritrea", type: "country" },
  { name: "Djibouti", type: "country" },
  { name: "Comoros", type: "country" },
  { name: "Cape Verde", type: "country" },
  { name: "São Tomé and Príncipe", type: "country" },
  { name: "Lesotho", type: "country" },
];
